### ISSUE TITLE
windows找不到笔记的文件

### ISSUE THREAD

**Issue by Echo0129** [LGUCourses/LGU-Course#1]
是不是没把笔记的文件传上来捏 还是我不会操作
<img width="337" alt="image" src="https://user-images.githubusercontent.com/114634209/197324699-b6e60d98-ff98-4356-b211-58d8814ca1bc.png">

**Comment by yuantuo666** [comment]
- 进入网站可以看到 https://lgucourses.github.io/LGU-Course/
- 或者 clone 到本地后 checkout 到 gh-pages 分支

**Comment by Echo0129** [comment]
okok谢谢
